version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/ui"
    target-branch: "develop"
    reviewers:
      - "@f-eld-ch/Reviewers"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
    labels:
      - "npm"
      - "dependencies"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    target-branch: "develop"
    reviewers:
      - "@f-eld-ch/Reviewers"    
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"

  # Enable version updates for Go
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    reviewers:
      - "@f-eld-ch/Reviewers"    
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
    labels:
      - "gomod"
      - "dependencies"
      
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    reviewers:
      - "@f-eld-ch/Reviewers"    
    schedule:
      interval: "daily"
      time: "20:00"
    labels:
      - "gh-actions"
      - "dependencies"
