name: Build & Test & Push Image
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CHANGELOG_APP_ID }}
          private-key: ${{ secrets.CHANGELOG_APP_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Commit
        run: |
          git checkout ${GITHUB_REF_NAME}
          git config user.name 'f-eld-ch-changelog[bot]'
          git config user.email 'f-eld-ch-changelog[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore(changelog): Update changelog [skip ci]"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ${GITHUB_REF_NAME}
