name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/RedGecko/sitrep
          tags: |
            # set latest tag for default branch / ordered by priority
            type=raw,value=stable,enable=${{ github.ref == format('refs/heads/{0}', 'main') }},priority=910
            # priority 900
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
            # priority 700
            type=edge,branch=develop
            # priority 600
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-,enable=true
            # priority 100
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            GIT_SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
      - name: Docker meta for hasura
        id: meta-hasura
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/RedGecko/sitrep-hasura
          tags: |
            # set latest tag for default branch
            type=edge,branch=develop
            type=raw,value=stable,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-,enable=true,priority=600
            type=semver,pattern={{version}},prefix=v,priority=420
            type=semver,pattern={{major}}.{{minor}},prefix=v,priority=410
            type=semver,pattern={{major}},prefix=v,priority=400
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.hasura
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-hasura.outputs.tags }}
          labels: ${{ steps.meta-hasura.outputs.labels }}
