name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/RedGecko/sitrep
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            - version=${{ steps.meta.outputs.version }}
            - gitsha=${{ env.GITHUB_SHA }}
      - name: Docker meta for hasura
        id: meta-hasura
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/RedGecko/sitrep-hasura
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.hasura
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-hasura.outputs.tags }}
          labels: ${{ steps.meta-hasura.outputs.labels }}
