name: PR Conventional Commit Validation
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write
  repository-projects: read
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: f-eld-ch/PRConventionalCommits@main
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert", "security"]'
